FROM nginx:stable
WORKDIR /work
EXPOSE 443
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
COPY ./cert/server.cert ./cert/server.privkey ./
COPY ./cert/ca.cert /etc/ssl/certs/
RUN echo ca.cert >> /etc/ca-certificats.conf && update-ca-certificates
COPY ./origin/proxy.conf /etc/nginx/conf.d/
COPY ./origin/index.html /var/www/html/
