version: '3.7'
services:
  origin.local:
    build:
      context: ./
      dockerfile: Dockerfile-origin

  amppkg.local:
    build:
      context: ./
      dockerfile: Dockerfile-amppkg

  reverse.local:
    build:
      context: ./
      dockerfile: Dockerfile-reverse
    ports:
      - "443:443"
    networks:
      default:
        aliases:
          - try-amppackager.local
